apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: backend
  namespace: __MONITORING_NAMESPACE__
spec:
  namespaceSelector:
    matchNames:
      - __APP_NAMESPACE__
  selector:
    matchLabels:
      app: backend
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
